Add separate queue for migration deposits
UNC-Libraries/Carolina-Digital-Repository pull request #1156
Opened 2020-11-30 18:47 UTC by lfarrell

https://jira.lib.unc.edu/browse/BXC-2940

2020-11-30 20:32 UTC, bbpennel requested changes
This looks good, added one comment. One other thought, another option would be to queue the migration deposits as a different priority. Maybe `Priority.low` since we aren't using that at the moment and we don't want them to compete with the user submitted deposits. Do you have any preference between that approach and the current approach of checking the packaging type?

2020-11-30 20:32 UTC, bbpennel commented on deposit/src/main/webapp/WEB-INF/service-context.xml
> +        <constructor-arg name="numWorkers" value="${workers.high.num:4}" />
Could you give this a separate property, probably `workers.migration.num` and set its default to 2?

2020-11-30 21:13 UTC, lfarrell commented
Either way's fine with me, depositType or priority

2020-12-03 14:15 UTC, bbpennel requested changes

2020-12-03 14:15 UTC, bbpennel commented on deposit/src/main/java/edu/unc/lib/deposit/work/DepositSupervisor.java
> +        PREPARE, DELAYED_PREPARE, CDRMETSCONVERT, PREPARE_HIGH_PRIORITY, PREPARE_MIGRATION;
Sorry to be a pain, but since you've gone with the `low` priority thing, I'd suggest naming the queue `PREPARE_LOW_PRIORITY` as well

2020-12-03 14:15 UTC, bbpennel commented on deposit/src/main/webapp/WEB-INF/service-context.xml
> +        <constructor-arg name="numWorkers" value="${workers.migration.num:2}" />
similarly, i would name the property `workers.low.num` now

2020-12-11 23:36 UTC, bbpennel approved these changes

2020-12-14 15:09 UTC, merged