Display search parameters as tags
UNC-Libraries/Carolina-Digital-Repository pull request #1272
Opened 2021-07-06 14:23 UTC by lfarrell

https://jira.lib.unc.edu/browse/BXC-3198

2021-07-07 18:30 UTC, bbpennel requested changes
This works well. Left a few cleanup comments, plus some extra tests and few minor bugs

2021-07-07 18:30 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/searchWrapper.vue
> -                this.collection = UUID_REGEX.test(this.$route.path) ? this.$route.path.split('/')[2] : '';
I wonder if we should keep this logic? It allows scoping a search result to containers other than collections, which I personally find kind of helpful, and we might want to expose again later or in conjunction with adding more faceting/search options to the result pages.

2021-07-07 18:30 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/facetTags.spec.js
> +        wrapper.vm.$router.push('/search/?collection=d77fd8c9-744b-42ab-8e20-5ad9bdf8194e');
for what its worth, the urls i'm seeing in the live interface are in the form `/search?...` rather than `search/?...`

2021-07-07 18:30 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/facetTags.spec.js
> +        expect(selected_tags.at(0).text()).toMatch(/testCollection/);
Might be good to verify that it is displaying `Collection > testCollection` and `Format > image` to make sure the type labels are present and on the right terms

2021-07-07 18:30 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/facetTags.spec.js
> +});
Add tests for one of the date term fields to make sure the formatting is working.

2021-07-07 18:30 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/facetTags.spec.js
> +});
Also add test for searching the title index, and searching both the title and the keyword index at the same time.

2021-07-08 14:21 UTC, bbpennel requested changes

2021-07-08 14:21 UTC, bbpennel commented on static/js/vue-cdr-access/src/components/filterTags.vue
> +        formatSearchValue(field, fieldValue) {
I think you renamed the wrong variable? It looks like `field` is the value of the field, while `type` (now `fieldValue`) is the name of the parameter from the query string.

2021-07-08 14:21 UTC, bbpennel commented on static/js/vue-cdr-access/tests/unit/filterTags.spec.js
> +        expect(selected_tags.at(0).text()).toMatch(/Collection.*?testCollection/s);
Just curious, what does the `/s` do here? I was having a hard time looking it up

2021-07-08 14:52 UTC, lfarrell commented on static/js/vue-cdr-access/tests/unit/filterTags.spec.js
> +        expect(selected_tags.at(0).text()).toMatch(/Collection.*?testCollection/s);
It allows the . in a regex to match the  \n character. Don't know why it doesn't by default  `¯\_(ツ)_/¯`

2021-07-08 17:09 UTC, bbpennel approved these changes

2021-07-08 18:24 UTC, merged